### ISSUE TITLE
This extension blocks the context menu of "preview image" nodes

### ISSUE THREAD

**Issue by JPS-GER** [BlakeOne/ComfyUI-NodePresets#1]
Enabling this extension blocks the context menu of "preview image" nodes. 

Right click on "preview image" doesn't show any menu.

Your second extension (ResetDefaults) doesn't have that problem.

**Comment by BlakeOne** [comment]
Okay it should work now with nodes like "preview image" that don’t have any widget inputs. I removed the option from the menu for my other extension [NodeReset](https://github.com/BlakeOne/ComfyUI-NodeReset) for these nodes as well, since it doesn't have any effect in this case anyway. Thanks for reporting. :)

**Comment by JPS-GER** [comment]
Working fine now. Thanks for the fast fix.
